
const log = {
  Bosses: {
    "Abyssal Sire": { items: [], killCount: 0 },
    "Alchemical Hydra": { items: [], killCount: 0 },
    "Barrows Chests": { items: [], killCount: 0 },
    Bryophyta: { items: [], killCount: 0 },
    "Callisto and Artio": { items: [], killCount: 0 },
    Cerberus: { items: [], killCount: 0 },
    "Chaos Elemental": { items: [], killCount: 0 },
    "Chaos Fanatic": { items: [], killCount: 0 },
    "Commander Zilyana": { items: [], killCount: 0 },
    "Corporeal Beast": { items: [], killCount: 0 },
    "Crazy Archaeologist": { items: [], killCount: 0 },
    "Dagannoth Kings": { items: [], killCount: 0 },
    "Duke Sucellus": { items: [], killCount: 0 },
    "General Graardor": { items: [], killCount: 0 },
    "Giant Mole": { items: [], killCount: 0 },
    "Grotesque Guardians": { items: [], killCount: 0 },
    Hespori: { items: [], killCount: 0 },
    "Kalphite Queen": { items: [], killCount: 0 },
    "King Black Dragon": { items: [], killCount: 0 },
    Kraken: { items: [], killCount: 0 },
    "Kree'arra": { items: [], killCount: 0 },
    "K'ril Tsutsaroth": { items: [], killCount: 0 },
    Nex: { items: [], killCount: 0 },
    Obor: { items: [], killCount: 0 },
    "Phantom Muspah": { items: [], killCount: 0 },
    Sarachnis: { items: [], killCount: 0 },
    Scorpia: { items: [], killCount: 0 },
    Skotizo: { items: [], killCount: 0 },
    Tempoross: { items: [], killCount: 0 },
    "The Fight Caves": { items: [], killCount: 0 },
    "The Gauntlet": { items: [], killCount: 0 },
    "The Inferno": { items: [], killCount: 0 },
    "The Leviathan": { items: [], killCount: 0 },
    "The Nightmare": { items: [], killCount: 0 },
    "Thermonuclear Smoke Devil": { items: [], killCount: 0 },
    "The Whisperer": { items: [], killCount: 0 },
    Vardorvis: { items: [], killCount: 0 },
    "Venenatis and Spindel": { items: [], killCount: 0 },
    "Vet'ion and Calvar'ion": { items: [], killCount: 0 },
    Vorkath: { items: [], killCount: 0 },
    Wintertodt: { items: [], killCount: 0 },
    Zalcano: { items: [], killCount: 0 },
    Zulrah: { items: [], killCount: 0 },
  },
  Clues: {
    "Beginner Treasure Trails": { items: [], killCount: 0 },
    "Easy Treasure Trails": { items: [], killCount: 0 },
    "Elite Treasure Trails": { items: [], killCount: 0 },
    "Elite Treasure Trails (Rare)": { items: [], killCount: 0 },
    "Hard Treasure Trails": { items: [], killCount: 0 },
    "Hard Treasure Trails (Rare)": { items: [], killCount: 0 },
    "Master Treasure Trails": { items: [], killCount: 0 },
    "Master Treasure Trails (Rare)": { items: [], killCount: 0 },
    "Medium Treasure Trails": { items: [], killCount: 0 },
    "Shared Treasure Trail Rewards": { items: [], killCount: 0 },
  },
  Minigames: {
    "Barbarian Assault": { items: [], killCount: 0 },
    "Brimhaven Agility Arena": { items: [] },
    "Castle Wars": { items: [] },
    "Fishing Trawler": { items: [] },
    "Giants' Foundry": { items: [], killCount: 0 },
    "Gnome Restaurant": { items: [], killCount: 0 },
    "Guardians of the Rift": { items: [], killCount: 0 },
    "Hallowed Sepulchre": { items: [], killCount: 0 },
    "Last Man Standing": { items: [], killCount: 0 },
    "Magic Training Arena": { items: [] },
    "Mahogany Homes": { items: [] },
    "Pest Control": { items: [] },
    "Rogues' Den": { items: [] },
    "Shades of Mort'ton": { items: [] },
    "Soul Wars": { items: [], killCount: 0 },
    "Temple Trekking": { items: [] },
    "Tithe Farm": { items: [] },
    "Trouble Brewing": { items: [] },
    "Volcanic Mine": { items: [] },
  },
  Other: {
    "Aerial Fishing": { items: [] },
    "All Pets": { items: [] },
    Camdozaal: { items: [] },
    "Champion's Challenge": { items: [] },
    "Chaos Druids": { items: [] },
    "Chompy Bird Hunting": { items: [] },
    "Creature Creation": { items: [] },
    Cyclopes: { items: [] },
    Forestry: { items: [] },
    "Fossil Island Notes": { items: [] },
    "Glough's Experiments": { items: [], killCount: 0 },
    Miscellaneous: { items: [] },
    "Monkey Backpacks": { items: [] },
    "Motherlode Mine": { items: [] },
    "My Notes": { items: [] },
    "Random Events": { items: [] },
    Revenants: { items: [], killCount: 0 },
    "Rooftop Agility": { items: [] },
    "Shayzien Armour": { items: [] },
    "Shooting Stars": { items: [] },
    "Skilling Pets": { items: [] },
    Slayer: { items: [] },
    TzHaar: { items: [] },
  },
  Raids: {
    "Chambers of Xeric": { items: [], killCount: 0 },
    "Theatre of Blood": { items: [], killCount: 0 },
    "Tombs of Amascut": { items: [], killCount: 0 },
  },
};

export default log;